<a href="https://colab.research.google.com/github/cmdshati/AI_Resolution/blob/main/Day_02_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
list = [1,2,3,4,5,6]
list

[1, 2, 3, 4, 5, 6]

# Array Creation

In [ ]:
import numpy as np
list = [1,2,3,4,5,6]
arr1 = np.array(list)
print(arr1)

[1 2 3 4 5 6]


# 2D array creation

In [ ]:
a = [1,2,3,4]
b =[4,5,6,7]
c=[9,0,8,8]

arr2= np.array([a,b,c])
print(arr2)


[[1 2 3 4]
 [4 5 6 7]
 [9 0 8 8]]


# 3D array creation

In [ ]:
a = [1,2,3,4]
b =[4,5,6,7]
c=[9,0,8,8]

arr3 = np.array([[a,b,c],[a,b,c]])
print(arr3)


[[[1 2 3 4]
  [4 5 6 7]
  [9 0 8 8]]

 [[1 2 3 4]
  [4 5 6 7]
  [9 0 8 8]]]


# Initial PlaceHolder - arange, zeros, ones, full, random

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.arange(6).reshape(2,3))
 # reshape(row,column)
# create 3d array using reshape
print("3d array")
print(np.arange(12).reshape(2,2,3))


[[0 1 2]
 [3 4 5]]
3d array
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
print(np.zeros([2,2,5],int))
np.zeros(7)
np.zeros(7,int)

[[[0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]]]


array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
print(np.ones([2,3,4],int))
np.ones(7)
np.ones(7,int)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


array([1, 1, 1, 1, 1, 1, 1])

In [ ]:
print(np.full([2,2,4],5))
np.full(6,5)

[[[5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]]]


array([5, 5, 5, 5, 5, 5])

In [ ]:
a =np.arange(10,25,2).reshape(2,4)  # start, end, step
print(a)

[[10 12 14 16]
 [18 20 22 24]]


In [ ]:
twoDzeros = np.zeros([2,5],int)
print(twoDzeros)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
zeros = np.zeros(10,int)
print(zeros)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
d_one = np.ones([2,5],int)
print(d_one)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
one = np.ones(8,int)
print(one)

[1 1 1 1 1 1 1 1]


In [ ]:
full = np.full(5,5)
print(full)

[5 5 5 5 5]


In [ ]:
full2d = np.full([2,5],5.0)
print(full2d)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [ ]:
randarray = np.random.random([2,5])
print(randarray)
np.random.rand(5)
np.random.rand(2,5)

[[0.15741849 0.40122004 0.33752477 0.18368288 0.13554903]
 [0.48144691 0.00095144 0.06644232 0.85517095 0.92635267]]


array([[0.39122916, 0.15056742, 0.09406156, 0.40213606, 0.29392987],
       [0.82809858, 0.01484289, 0.66402102, 0.63658788, 0.21096962]])

In [ ]:
np.random.randint(10)
# Single random integer between 0 and 9


3

In [ ]:
np.random.randint(10,20)
# Single random integer between 10 and 19

18

In [ ]:
np.random.randint(10,20,5)
# size = 5 means  "5" random integer between 10 and 19

array([11, 17, 15, 15, 13])

In [ ]:
np.random.randint(100,200,10)
# size = 10 random integer between  100 to 199

array([149, 191, 167, 106, 163, 116, 134, 138, 159, 134])

# eye **function**

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
a =[6,8,9,4,2,0,1]
print(np.sort(a))

[0 1 2 4 6 8 9]


In [ ]:
a =[9,0,8]
b=[7,9,5]
x = np.array([a,b])
print(x)
print(np.sort(x,axis=0))
print(np.sort(x,axis=1))


[[9 0 8]
 [7 9 5]]
[[7 0 5]
 [9 9 8]]
[[0 8 9]
 [5 7 9]]


# **Manipulation in array**

In [ ]:
print(np.append([[1,2,3],[4,5,6]],[[7,8,9]],axis = 0))
# axis 0 means rowwise add ..


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:

print(np.append([[1,2,3],[4,5,6]],[[7],[8]],axis=1))
# axis 1 means column wise value add

[[1 2 3 7]
 [4 5 6 8]]


In [ ]:
print(np.insert([1,2,3,4], 1 ,99))

[ 1 99  2  3  4]


In [ ]:
print(np.insert([[1,2,3],[3,4,5]], 1, [7,8,9],axis=0))

[[1 2 3]
 [7 8 9]
 [3 4 5]]


In [ ]:
np.insert([[1,2,],[3,4]],1 ,[5,6],axis =0)
np.insert([[1,2,4],[3,4,6]],1 ,[5,6],axis =1)
# insert column accroding to number of rows..if number of rows is 2 insert two value like [6,7] but if nuber of rows is 3 insert value like [0,9,8]
print(np.insert([[1,2,4],[3,4,6],[7,9,0]],1 ,[5,6,12],axis =1))

[[ 1  5  2  4]
 [ 3  6  4  6]
 [ 7 12  9  0]]


# Delete element

In [ ]:

# 3 means delete elemnt of index 3
print(np.delete([1,2,3,4],3) )

[1 2 3]


# Delete eelment from 2D array

In [ ]:
print(np.delete([[1,2,3],[6,8,8],[9,0,9]],1,axis =0))
# row wise delete

[[1 2 3]
 [9 0 9]]


In [ ]:
# column wise delete
print(np.delete([[1,2,3],[6,8,8],[9,0,9]],1,axis =1))

[[1 3]
 [6 8]
 [9 9]]


# Copy Array :Method 1 :Normal Assignment , Method 2 : Copy  , Method 3  : view

In [ ]:
list = [1,2,3,45]
arr1 = np.array(list)

# Normal Assignment
new_array = arr1
# before change
print("before change of new_array")
print(new_array)
print(arr1)

new_array[0]=100
print(new_array)
print(arr1)
if(id(arr1)==id(new_array)):
    print("same")
else:
    print("not same")





before change ogf new_array
[ 1  2  3 45]
[ 1  2  3 45]
[100   2   3  45]
[100   2   3  45]
same


# Method  2 : Copy

In [ ]:
list = [1,2,3,4]
arr1 = np.array(list)

arr2 = np.copy(arr1)

print(arr1)
print(arr2)

arr2[3]=67

if(id(arr1)==id(arr2)):
    print("same")
else:
    print("not same")

print(arr1)
print(arr2)



[1 2 3 4]
[1 2 3 4]
not same
[1 2 3 4]
[ 1  2  3 67]


# Method 3 View

In [ ]:
list = [1,2,3,4]
arr1 = np.array(list)

arr2 = arr1.view()

print(arr1)
print(arr2)

arr2[3]=67

if(id(arr1)==id(arr2)):
    print("same")
else:
    print("not same")

print(arr1)
print(arr2)



[1 2 3 4]
[1 2 3 4]
not same
[ 1  2  3 67]
[ 1  2  3 67]


# Comaprison Operator

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([2,2,3,4,7])
print(a>b)
print(a==b)
print(a!=b)
print(a<b)
print(a>=b)
print(a<=b)
print(a>2)


[False False False False False]
[False  True  True  True False]
[ True False False False  True]
[ True False False False  True]
[False  True  True  True False]
[ True  True  True  True  True]
[False False  True  True  True]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([2,2,3,4,7])
print(a==b)
# check elementwise true false
print(np.array_equal(a,b))
# check the whole array


[False  True  True  True False]
False


## Indexing, Slicing, Subsettng in an array

In [ ]:
a = np.array([[1,2,3],[8,9,0]])
print(a)
# indexing
print(a[1,0])

print(a[[0,0,1],[0,1,1]])

x =  np.array([1,9,0,7])
print(x[0])

x[0] = 8
print(x)

# Slicing
print(x[2:])
print(x[:-2])

print(x[-2:])


[[1 2 3]
 [8 9 0]]
8
[1 2 9]
1
[8 9 0 7]
[0 7]
[8 9]
[0 7]


# Slicing in 2D Array

In [ ]:
a = np.array([[25,18,45,89,13],
              [90,78,56,34,67],
              [34,67,87,98,34]])
print(a)

# Get the second row (index 1)
print(a[1,:])
# get the third column ( index  2)
print(a[:, 2])

# get  all rows from 1 to last
print(a[1:,])

# Extracting Submatrices
#  Get rows 0 to 1, and columns 0 to 2
print(a[0:2,0:3])

# negative  slicing
print(a[-1:,])
print(a[:,-1])

print(a[:,1])

[[25 18 45 89 13]
 [90 78 56 34 67]
 [34 67 87 98 34]]
[90 78 56 34 67]
[45 56 87]
[[90 78 56 34 67]
 [34 67 87 98 34]]
[[25 18 45]
 [90 78 56]]
[[34 67 87 98 34]]
[13 67 34]
[18 78 67]


# np.fromiter : Creates an array from an iterable object . It bulid only  1 Dimnesioanl array . To create 2D ar 3D array first create 1D array then reshape it using reshape method. It has parameters like (iterable object, dtype, count for specifying item)

In [ ]:
square = (x * x for x in range(5))

array = np.fromiter(square,dtype=int)
print(array)

[ 0  1  4  9 16]


In [ ]:
square = (x * x for x in range(10))

array = np.fromiter(square,dtype=int)
print(array)

[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
square = (x * x for x in range(10))

# use of count parameter
array = np.fromiter(square,dtype=int ,count=2)
print(array)

[0 1]


In [ ]:
# use of empty without intilazing entries .
# values ae random garbage from memory
print(np.empty(4))

[4.0e-323 4.4e-323 0.0e+000 3.5e-323]


In [ ]:
print(np.empty([5,3],int))

[[25 18 45]
 [89 13 90]
 [78 56 34]
 [67 34 67]
 [87 98 34]]


# Use of np.random.randint . Generate random inetegers  and also to create a array (1D array , 2D array, 3D array)

In [ ]:
np.random.randint(10)
# Generates a single integer from 0 to 9

8

In [ ]:
np.random.randint(4,15)
# Generates a single integer from 4 to 14

12

In [ ]:
np.random.randint(4,15,10)
# start , stop, size
# Generates an 1-D array  of size 10 from 4 to 14


array([14,  7,  8, 10, 12,  4, 11,  5,  8, 12])

In [ ]:
# craete 2d array
np.random.randint(1,10,[3,3])

array([[3, 8, 6],
       [9, 9, 5],
       [6, 6, 1]])

In [ ]:
print(np.random.randint(1,10,[2,3,3]))

[[[7 5 4]
  [1 1 5]
  [4 9 7]]

 [[1 4 9]
  [3 3 2]
  [2 1 1]]]


In [ ]:
np.random.rand()

0.15557750282823302

In [ ]:
np.random.rand(5)

array([0.15413386, 0.09183048, 0.35704367, 0.60142883, 0.05110627])

In [ ]:
np.random.rand(4,3)

array([[0.24003816, 0.77214514, 0.20532786],
       [0.91561639, 0.05006287, 0.52896044],
       [0.53791394, 0.1094798 , 0.79614679],
       [0.84297315, 0.28266664, 0.97813275]])

In [ ]:
x = np.save("test", np.full([2,2,3],5))
# a = np.load("test.npy")
print(x)

None


In [ ]:
np.save("test", np.full([2,3],5))
np.save("test", np.full(6,5))
np.save("test", np.full([2,2,3],5))
a = np.load("test.npy")
print(a)

[[[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
x = np.delete(a,1,axis=0)
print(x)
y = np.delete(a,2,axis =1)
print(y)
# flatten input convert 2d array to 1 Dimensional array
print(a.flatten())
a = np.array([[[1,2,3],[1,4,5],[4,5,7]]])
print(a)
print(a.flatten())


[[1 2 3]
 [4 5 6]]
[[1 2 3]]
[[1 2]
 [4 5]]
[1 2 3 4 5 6]
[[[1 2 3]
  [1 4 5]
  [4 5 7]]]
[1 2 3 1 4 5 4 5 7]


## Numpy array Manipulation

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))
print(np.concatenate((arr1,arr2),axis =0))

# Using stack creates 2d array from 1d array and creates 3D array from 2D array .
print(np.stack((arr1,arr2),axis =0))
print(np.stack((arr1,arr2),axis =1))





[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# stacking two 1D arrays will produce a 2D array, and stacking multiple 2D arrays will produce a 3D array

In [ ]:
arr1 = np.array([[1,2,3],[7,8,9]])
arr2 = np.array([[4,5,6],[0,9,5]])
print(np.concatenate((arr1,arr2),axis =0))
print(np.concatenate((arr1,arr2),axis =1))
print(np.concatenate((arr1,arr2),axis =None))
print(np.stack((arr1,arr2),axis =0))
print(np.stack((arr1,arr2),axis =1))
print(np.stack((arr1,arr2),axis =2))






[[1 2 3]
 [7 8 9]
 [4 5 6]
 [0 9 5]]
[[1 2 3 4 5 6]
 [7 8 9 0 9 5]]
[1 2 3 7 8 9 4 5 6 0 9 5]
[[[1 2 3]
  [7 8 9]]

 [[4 5 6]
  [0 9 5]]]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 9 5]]]
[[[1 4]
  [2 5]
  [3 6]]

 [[7 0]
  [8 9]
  [9 5]]]


# Numpy Inspecting Properties

In [ ]:
arr1 = np.array([[1,2,3],[7,8,9]])
arr1.shape
len(arr1)
arr1.ndim
arr1.size
arr1.dtype
arr1 = arr1.astype("float")
arr1.dtype
arr1
arr1.itemsize

array([[1., 2., 3.],
       [7., 8., 9.]])